export const LOGIN_CHANGE  = 'LOGIN_CHANGE';

export const ORDER_CREATED_SUCCESS = 'ORDER_CREATED_SUCCESS';
export const ORDER_CREATED_FAIL = 'ORDER_CREATED_FAIL';
export const ORDER_FETCH_START = 'ORDER_FETCH_START';